In [1]:
#Numpy Practice Questions
#1. Define two custom numpy arrays, say A and B. Generate two new numpy arrays by stacking A and B vertically and horizontally.
#2. Find common elements between A and B. [Hint : Intersection of two sets]
#3. Extract all numbers from A which are within a specific range. eg between 5 and 10. [Hint: np.where() might be useful or boolean masks]
#4. Filter the rows of iris_2d that has petallength (3rd column) > 1.5 and sepallength (1st column) < 5.0
#	url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
#	iris_2d = np.genfromtxt(url, delimiter=',', dtype='float', usecols=[0,1,2,3])

In [2]:
import numpy as np

In [3]:
A = np.array([[5, 6], [3, 4]])
B = np.array([[1, 2], [3, 4]])
C = np.vstack((A, B)) #Vertical stack
D = np.hstack((A, B)) #Horizontal stack

print("A:")
print(A)

print("\nB:")
print(B)

print("\nC - Vertical stack:")
print(C)

print("\nD - Horizontal stack:")
print(D)


A:
[[5 6]
 [3 4]]

B:
[[1 2]
 [3 4]]

C - Vertical stack:
[[5 6]
 [3 4]
 [1 2]
 [3 4]]

D - Horizontal stack:
[[5 6 1 2]
 [3 4 3 4]]


In [4]:
common_elements = np.intersect1d(A, B)
print(common_elements)

[3 4]


In [5]:
indices = np.where((A >= 5) & ( A<= 10))
numbers = A[indices]
print(numbers)

[5 6]


In [7]:
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris_2d = np.genfromtxt(url, delimiter=',', dtype='float', usecols=[0,1,2,3])
condition = (iris_2d[:, 2] > 1.5) & (iris_2d[:, 0] < 5.0)
filtered_iris = iris_2d[condition]
print("Filtered rows")
print(filtered_iris)

Filtered rows
[[4.8 3.4 1.6 0.2]
 [4.8 3.4 1.9 0.2]
 [4.7 3.2 1.6 0.2]
 [4.8 3.1 1.6 0.2]
 [4.9 2.4 3.3 1. ]
 [4.9 2.5 4.5 1.7]]


In [8]:
#Practice Questions for Pandas
#1. From df filter the 'Manufacturer', 'Model' and 'Type' for every 20th row starting from 1st (row 0).
#```
#df = pd.read_csv('https://raw.githubusercontent.com/selva86/datasets/master/Cars93_miss.csv')
#```
#2. Replace missing values in Min.Price and Max.Price columns with their respective mean.
#```
#df = pd.read_csv('https://raw.githubusercontent.com/selva86/datasets/master/Cars93_miss.csv')
#```
#3. How to get the rows of a dataframe with row sum > 100?
#```
#df = pd.DataFrame(np.random.randint(10, 40, 60).reshape(-1, 4))

In [9]:
import pandas as pd

In [10]:
df = pd.read_csv('https://raw.githubusercontent.com/selva86/datasets/master/Cars93_miss.csv')
every_20th_row = df.iloc[::20]
filtered_df = every_20th_row[['Manufacturer', 'Model', 'Type']]
print(filtered_df)

   Manufacturer    Model     Type
0         Acura  Integra    Small
20     Chrysler  LeBaron  Compact
40        Honda  Prelude   Sporty
60      Mercury   Cougar  Midsize
80       Subaru   Loyale    Small


In [11]:
df = pd.read_csv('https://raw.githubusercontent.com/selva86/datasets/master/Cars93_miss.csv')
min_price_mean = df['Min.Price'].mean()
df['Min.Price'].fillna(min_price_mean, inplace=True)
max_price_mean = df['Max.Price'].mean()
df['Max.Price'].fillna(max_price_mean, inplace=True)
print(df[['Min.Price', 'Max.Price']])

    Min.Price  Max.Price
0   12.900000  18.800000
1   29.200000  38.700000
2   25.900000  32.300000
3   17.118605  44.600000
4   17.118605  21.459091
..        ...        ...
88  16.600000  22.700000
89  17.600000  22.400000
90  22.900000  23.700000
91  21.800000  23.500000
92  24.800000  28.500000

[93 rows x 2 columns]


In [12]:
df = pd.DataFrame(np.random.randint(10, 40, 60).reshape(-1, 4))
row_sums = df.sum(axis=1)
rows_with_sum_over_100 = df[row_sums > 100]
print(rows_with_sum_over_100)

     0   1   2   3
2   36  27  36  22
10  31  26  27  24
12  24  19  20  38
